### ISSUE TITLE
Дописать речевые модули для продаж 

### ISSUE THREAD

**Issue by VaderMann** [AuthFailed/flomaster#20]
Рм-ы продаж

**Comment by VaderMann** [comment]
Могу вам предложить приобрести новый роутер у нас, гарантия 3 года, в случае ограничений в работе роутера будет произведена бесплатная замена

Модель: TP-Link Archer EC220

- Скорость по кабелю: до 1000 Мбит/с
- Поддерживаемый стандарт WI-FI: 802.11AC
- Площадь покрытия: до 70 м2
- Гарантия: 3 года
- Подходит для любого провайдера

Стоимость:
- В собственность - 4 490 ₽
- В рассрочку:
- 825 ₽/мес. на 6 месяцев (общая стоимость - 4 950 ₽)

**Comment by VaderMann** [comment]
Могу вам предложить приобрести новый роутер у нас, гарантия 3 года, в случае ограничений в работе роутера будет произведена бесплатная замена

Модель: TP-Link Archer EX220

- Скорость по кабелю: до 1000 Мбит/с
- Поддерживаемый стандарт WI-FI: 802.11AX
- Площадь покрытия: до 80 м2
- Гарантия: 4 года
- Подходит для любого провайдера

Стоимость:
- В собственность - 6 800 ₽
- В рассрочку:
- 1 270 ₽/мес. на 6 месяцев (общая стоимость - 7 620 ₽)

**Comment by VaderMann** [comment]
Могу вам предложить приобрести новый роутер у нас, гарантия 4 года, в случае ограничений в работе роутера будет произведена бесплатная замена

Модель: TP-Link Archer AX55

- Скорость по кабелю: до 1000 Мбит/с
- Поддерживаемый стандарт WI-FI: 802.11AX
- Площадь покрытия: до 80 м2
- Гарантия: 4 года
- Подходит для любого провайдера

Стоимость:
- В собственность - 8 900 ₽
- В рассрочку:
- 1 650 ₽/мес. на 6 месяцев (общая стоимость - 9 900 ₽)

**Comment by AuthFailed** [comment]
Требуется добавление речевых модулей на подведение к продаже. РМы с характеристиками роутеров, приставок и камер готовы

**Comment by AuthFailed** [comment]
Перенесено в [планер](https://planer.chrsnv.ru/spaces/issues/5e583276999e4698a27d703f8b7bfea0)
